# IaC Logic App resources deployment template
trigger:
- main

jobs:
- deployment: deploy_logicapp_resources
  displayName: Deploy Logic App Resources
  environment: 'dev'
  variables:
    deploymentMode: 'Incremental'
    environment: 'dev'
  strategy:
    runOnce:
      deploy:
        steps:
        - download: current
          # artifact: $(artifactName)

        - task: AzureResourceGroupDeployment@2
          displayName: 'Deploy Logic App'
          inputs:
            azureSubscription: 'ca543220-3d63-4b72-a9a0-4b43f15707ff'
            resourceGroupName: 'rg-test'
            location: 'eastus'
            csmFile: '$(Pipeline.Workspace)/template.json'
            overrideParameters:
              -location eastus
              -environmentName $(environment)
              -projectName azure-job-logic-app
              -logicAppName my-logic
            deploymentMode: $(deploymentMode)
            deploymentOutputs: LogicAppArmOutputs
