# IaC Logic App resources deployment template
trigger:
- main

jobs:
- deployment: deploy_logicapp_resources
  displayName: Deploy Logic App Resources
  pool:
    vmImage: ubuntu-18.04  
  environment: 'dev'
  variables:
    deploymentMode: 'Incremental'
    environment: 'dev'
  strategy:
    runOnce:
      deploy:
        steps:
        - download: current
          # artifact: $(artifactName)

        - task: AzureResourceGroupDeployment@2
          displayName: 'Deploy Logic App'
          inputs:
            azureSubscription: '7626e9c6-de92-4162-87bc-a5faf0b1721c'
            resourceGroupName: 'rg-test'
            location: 'eastus'
            csmFile: '$(Pipeline.Workspace)/template.json'
            overrideParameters:
              -location eastus
              -environmentName $(environment)
              -projectName azure-job-logic-app
              -logicAppName my-logic
            deploymentMode: $(deploymentMode)
            deploymentOutputs: LogicAppArmOutputs
